shawntabrizi/substrate-collectables-workshop

- custom/custom.css
> increase base font size

- 1/1.2-creating-a-storage-value.md
- 1/assets/1.2-template.rs
Adding correct import path for srml/support
> Fixed imports of srm/supprt module

- README.md
Note that on macOS when running locally it still doesn't show the menu items
> docs: Relates to #7. Add contribution guide

- README.md
Original steps are a little verbose.
@ltfschoen take a look and tell me what you think
> Simplify contribution seteps

- 0/0.3-interacting-with-your-node.md
- 0/0.4-common-patterns-moving-forward.md
- 1/1.0-introduction.md
- 1/1.1-creating-a-module.md
- 1/1.2-creating-a-storage-value.md
- 1/1.5-viewing-a-storage-mapping.md
> Some minor fixes I found while walking through

- 0/interacting-with-your-node.md
- 1/introduction.md
- 1/storage-mapping.md
Nothing substantial, just a few small errors
> Fixed some typos

- 1/assets/1.6-finished-code.rs
- 1/storing-a-structure.md
- 2/assets/2.1-finished-code.rs
- 2/assets/2.2-finished-code.rs
- 2/assets/2.2-template.rs
- 2/assets/2.3-finished-code.rs
- 2/assets/2.3-template.rs
- 2/assets/2.4-finished-code.rs
- 2/assets/2.4-template.rs
- 2/assets/2.5-finished-code.rs
- 2/assets/2.6-finished-code.rs
- 2/assets/2.6-template.rs
- 3/assets/3.1-finished-code.rs
- 3/assets/3.1-template.rs
- 3/assets/3.2-finished-code.rs
- 3/assets/3.2-template.rs
- 3/assets/3.3-finished-code.rs
- 3/assets/3.3-template.rs
- 3/assets/3.4-finished-code.rs
- 3/assets/3.4-template.rs
- 3/assets/3.5-finished-code.rs
Fixes https://github.com/shawntabrizi/substrate-collectables-workshop/issues/65
> Adjust code examples to new derive implementation

- 2/assets/2.1-template.rs
I forgot to save that file in the original PR  :|
> Change parity_codec_derive to parity_codec

- 4/rendering-kitties.md
Changed substratekitties-ui/**src/src**/KittyCards/ to substratekitties-ui/**src**/KittyCards/
> Removed extra src/ in the directory tree listing

- 3/assets/3.3-finished-code.rs
- 3/assets/3.3-template.rs
- 3/assets/3.4-finished-code.rs
- 3/assets/3.4-template.rs
- 3/assets/3.5-finished-code.rs
- 3/buying-a-kitty.md
@joepetrowski What do you think?
> Adding new content which addresses `buy_kitty` function

- 1/storage-mapping.md
Link to rust docs for `StorageMap` just like for `StorageValue`
> Update StorageMap link

- 3/assets/3.2-template.rs
checked_sub decreases not increases
> increment to decrement

- 1/storing-a-value.md
> Add module import hints for store-a-value chapter

- 2/tracking-all-kitties.md
> Update the wording around list iteration in the runtime

- README.md
Closes https://github.com/substrate-developer-hub/substrate-collectables-workshop/issues/119
> Make text ever so slightly more clear

- 1/introduction.md
- README.md
- _sidebar.md
- ja-jp/1/introduction.md
- ja-jp/_sidebar.md
- zh-cn/1/introduction.md
- zh-cn/_sidebar.md
Closes https://github.com/substrate-developer-hub/substrate-collectables-workshop/issues/120
> Fix navigation between languages

- 2/refactoring-our-code.md
The Rust code on this page had some errors so I fixed it. (Relies on specifying some imports correctly, but so did the original.)
Verified to (at least) compile in my personal branch of the workshop.
> fix Rust code in 'refactoring-our-code'

- 2/refactoring-our-code.md
> adjust Result types to avoid need for named import

- steps/18/README.md
- steps/20/README.md
- steps/27/README.md
- steps/40/README.md
- steps/41/README.md
- steps/42/README.md
- steps/43/README.md
- steps/50/README.md
- steps/8/README.md
> Fix grammatical errors and add docs hyperlinks

- steps/8/README.md
Closes: https://github.com/shawntabrizi/substrate-collectables-workshop/issues/182
> fix supertrait usage

- steps/11/README.md
> Fix wrong info on Hash Fingerprint
